spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/expensify
        username: abby
        password: lemon%phant4
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect